const database = {
movies: [    {
        id: 10,
        title: "Avengers:  Infinity War" ,
        year:  "2018",
        synopsis: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
        spoiler: "Spider-Man dies in this one",

    },
    {
        id: 11,
        title: "Avengers: Endgame",
        year: "2019",
        synopsis: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos's actions and undo the chaos to the universe, no matter what consequences may be in store.",
        spoiler: "Spider-Man comes back, but now Iron-Man is dead. :(",
    
    },
    {
        id: 12,
        title: "Looper",
        year: "2012",
        synopsis: "Joe is classified as a looper, a job in which his employers use time travel to send men from the future to be killed into the past, where Joe can properly dispose of their bodies.",
        spoiler: "He's been trying to kill himself the whole time!",
    },
    {
        id: 13,
        title: "Memento",
        year: "2000",
        synopsis: "A man with short-term memory loss attempts to track down his wife's murderer.",
        spoiler: "The one who really killed his wife was Leonard himself!",
    },
    {
        id: 14,
        title: "Black Swan",
        year: "2010",
        synopsis: " A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky's Swan Lake",
        spoiler: "She doesn't maintain her sanity, this girl is crazy.  She stabs herself in the gut.",
    },
    {
        id: 15,
        title: "Gone Girl",
        year: "2014",
        synopsis: "When his seemingly perfect wife Amy goes missing, philandering Nick becomes the prime suspect.",
        spoiler: "She faked her own murder and framed her husband",
    },
    {
        id: 16, 
        title: "Dirty Rotten Scoundrels",
        year: "1988",
        synopsis: "Two con men try to settle their rivalry by betting on who can swindle a young American heiress out of fifty thousand dollars first.",
        spoiler: "She was the one conning them the whole time.",
    },
    {
        id: 17,
        title: "The Prestige",
        year: "2006",
        synopsis: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
        spoiler: "The secret to the trick was it was two guys the whole time.  Christian Bale was actually twins.",
    },
    {
        id: 18,
        title: "It's a Wonderful Life",
        year: "1946",
        synopsis: "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.",
        spoiler: "He decides not to kill himeself.",

    },
    {
        id: 19,
        title: "The Sound of Music",
        year: "1965",
        synopsis: "A young novitiate is sent by her convent in 1930s Austria to become a governess to the seven children of a widowed naval officer.",
        spoiler: "The nun decides to marry this dude old enough to be her dad, then the Nazi's come and everyone has to go on a long hike.",   
    },
        {
        id: "",
        title: "" ,
        year:  "",
        synopsis: "",
        spoiler: "",
    },
    {
        id: 1,
        title: 'The Village' ,
        year: "2004",
        synopsis: "M Night Shyamalan makes another bad movie, but this time it takes place in a colonial village",
        spoiler: "The movie takes place in modern day, even though the villagers think they live in the past.  The monsters are just the village elders trying to scare the villagers into staying inside the town so they never find out about the modern world, and they reveal it halfway through the movie.  Noah dies, I don't remember how.",
    },
    {
        id: 2,
        title: "The Notebook" ,
        year:  "2004",
        synopsis: "Ryan Gosling and Rachel McAdams fall in love in the rain",
        spoiler: "Ryan Gosling and Rachel McAdams are an old couple and she has dementia. He tells her the story of how they fell in love and they imagine that they look like Ryan Gosling and Rachel McAdams but they probably didn't. Oh, and they both die at the end.",
    },
    {
        id: 3,
        title: "Titanic" ,
        year:  "1997",
        synopsis: "Leonardo DiCaprio is poor, Kate Winslet is rich, they both ride the Titanic",
        spoiler: "The titanic sinks. Sorry.  Oh, and Leo dies even though they both could have fit on the floating door. Also Kate gets old and they go on a multimillion dollar expedition to recover this rare diamond necklace she had.  When they find it, she throws it back in the ocean because reasons.",
    },
    {
        id: 4,
        title: "Star Wars Episode V: The Empire Strikes Back" ,
        year:  "1980",
        synopsis: "Luke, Leia, Han, and the gang get into more shenanigans as the stars continue to war",
        spoiler: "It's actually the second movie, not the fifth..............And Vader is Luke's dad.",
    },
    {
       id: 5,
       title: "Fight Club" ,
       year:  "1999",
       synopsis: "Edward Norton and Brad Pitt start a fight club.  Hilarity ensues",
       spoiler: "Edward Norton and Brad Pitt are the same guy.  And their fight club is actually an underground terrorist cell. They blow up a bunch of buildings in the end.",
    },
]
} 